import type { Metadata } from "next";
import "./globals.css";
import AutoThemeSwitcher from "./components/auto-theme-switcher";
import ManualThemeSwitcher from "./components/manual-theme-switcher";
import Profile from "./components/profile";
import RenderDotComAnalyticsComponents from "./components/render-dot-com-analytics-components";

export const metadata: Metadata = {
  title: "Shorten Url",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          {children}
          <AutoThemeSwitcher />
          <ManualThemeSwitcher />
          <Profile />
          <RenderDotComAnalyticsComponents />
      </body>
    </html>
  );
}
