import type { Metadata } from "next";
import "./globals.css";
import AutoThemeSwitcher from "./components/auto-theme-switcher";
import ManualThemeSwitcher from "./components/manual-theme-switcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AutoThemeSwitcher />
        <ManualThemeSwitcher />
        {children}
      </body>
    </html>
  );
}
